slang_general = {
    "7an": "tujuan",
    "@": "di",
    "ababil": "abg labil",
    "abis": "habis",
    "acc": "accord",
    "ad": "ada",
    "adlah": "adalah",
    "adlh": "adalah",
    "adoh": "aduh",
    "afaik": "as far as i know",
    "aha": "tertawa",
    "ahaha": "haha",
    "ahokncc": "ahok",
    "aing": "saya",
    "aj": "saja",
    "aja": "saja",
    "ajep-ajep": "dunia gemerlap",
    "ajj": "saja",
    "ak": "saya",
    "aka": "dikenal juga sebagai",
    "akhirx": "akhirnya",
    "akika": "aku",
    "akko": "aku",
    "akkoh": "aku",
    "akku": "aku",
    "akuwh": "aku",
    "akyu": "aku",
    "alay": "norak",
    "aljasa": "asal jadi saja",
    "alow": "halo",
    "ama": "sama",
    "ambilin": "ambilkan",
    "ambl": "ambil",
    "analisise": "analisis",
    "ancur": "hancur",
    "anjir": "anjing",
    "anjrit": "anjing",
    "ank": "anak",
    "anter": "antar",
    "ap": "apa",
    "ap2": "apa-apa",
    "apaan": "apa",
    "apasih": "apa sih",
    "ape": "apa",
    "apes": "sial",
    "aplot": "unggah",
    "aps": "apa",
    "apva": "apa",
    "aq": "saya",
    "aqu": "aku",
    "aquwh": "aku",
    "asap": "sesegera mungkin",
    "asbun": "asal bunyi",
    "aseek": "asyik",
    "aseekk": "asyik",
    "asek": "asyik",
    "asekk": "asyik",
    "aseknya": "asyiknya",
    "asem": "asam",
    "asoy": "asyik",
    "aspal": "asli tetapi palsu",
    "astrojim": "astagfirullahaladzim",
    "astul": "asal tulis",
    "ath": "kalau begitu",
    "ato": "atau",
    "atuh": "kalau begitu",
    "au ah": "tidak mau tahu",
    "ava": "avatar",
    "awak": "saya",
    "aws": "awas",
    "ay": "sayang",
    "ayang": "sayang",
    "ayank": "sayang",
    "ayok": "ayo",
    "b4": "sebelum",
    "bacot": "banyak bicara",
    "bakalan": "akan",
    "bales": "balas",
    "bandes": "bantuan desa",
    "bangdes": "pembangunan desa",
    "bangedh": "banget",
    "bangkotan": "tua",
    "banpol": "bantuan polisi",
    "banpres": "bantuan presiden",
    "banpur": "bantuan tempur",
    "bansarkas": "bantuan sarana kesehatan",
    "basbang": "basi",
    "bazis": "badan amal, zakat, infak, dan sedekah",
    "bcanda": "bercanda",
    "bcoz": "karena",
    "bdg": "bandung",
    "beb": "sayang",
    "begajulan": "nakal",
    "bejibun": "banyak",
    "beliin": "belikan",
    "belom": "belum",
    "benarjujur": "jujur",
    "bencong": "banci",
    "bener": "benar",
    "bentar": "sebentar",
    "ber2": "berdua",
    "ber3": "bertiga",
    "berdikari": "berdiri di atas kaki sendiri",
    "beresin": "membereskan",
    "bet": "banget",
    "bete": "bosan",
    "beti": "beda tipis",
    "beud": "banget",
    "beut": "banget",
    "bg": "abang",
    "bgd": "banget",
    "bgmn": "bagaimana",
    "bgs": "bagus",
    "bgt": "banget",
    "bgtt": "banget",
    "bgttt": "banget",
    "bhubu": "tidur",
    "bijimane": "bagaimana",
    "bimbuluh": "bimbingan dan penyuluhan",
    "bintal": "bimbingan mental",
    "bisi": "kalau-kalau",
    "bkl": "akan",
    "bkn": "bukan",
    "bknnya": "bukannya",
    "bl": "beli",
    "blegug": "bodoh",
    "blg": "bilang",
    "blh": "boleh",
    "blm": "belum",
    "bln": "bulan",
    "bls": "balas",
    "blum": "belum",
    "bnchi": "benci",
    "bnci": "benci",
    "bngung": "bingung",
    "bnran": "yang benar",
    "bnyk": "banyak",
    "bodor": "lucu",
    "bohay": "badan aduhai",
    "bokap": "ayah",
    "bokep": "porno",
    "boker": "buang air besar",
    "bokin": "pacar",
    "bokis": "bohong",
    "bole": "boleh",
    "boljug": "boleh juga",
    "bolot": "bodoh",
    "bonek": "bocah nekat",
    "bonyok": "ayah ibu",
    "boyeh": "boleh",
    "bpk": "bapak",
    "br": "baru",
    "brb": "segera kembali",
    "brg": "bareng",
    "brngkt": "berangkat",
    "bro": "saudara laki-laki",
    "brp": "berapa",
    "bru": "baru",
    "brur": "saudara laki-laki",
    "bs": "bisa",
    "bsa": "bisa",
    "bsen": "bosan",
    "bsk": "besok",
    "bt": "buat",
    "btw": "ngomong-ngomong",
    "bu_bu": "tidur",
    "buangbuang": "buang",
    "buaya": "tidak setia",
    "bubarin": "bubarkan",
    "bubbu": "tidur",
    "buber": "buka bersama",
    "bubu": "tidur",
    "bujubune": "luar biasa",
    "bumil": "ibu hamil",
    "buser": "buru sergap",
    "bw": "bawa",
    "bwhn": "bawahan",
    "bwt": "buat",
    "byar": "bayar",
    "byk": "banyak",
    "byr": "bayar",
    "byrin": "bayarkan",
    "c8": "chat",
    "cabal": "sabar",
    "cabut": "pergi",
    "cadas": "keren",
    "caem": "cakep",
    "calo": "makelar",
    "cama-cama": "sama-sama",
    "can": "belum",
    "cangcut": "celana dalam",
    "capcus": "pergi",
    "cape": "capek",
    "caper": "cari perhatian",
    "caur": "jelek",
    "cb": "coba",
    "ce": "cewek",
    "cekak": "tidak ada uang",
    "cekal": "cegah tangkal",
    "cekidot": "coba lihat",
    "cemen": "penakut",
    "cemplungin": "cemplungkan",
    "cengengesan": "tertawa",
    "ceper": "pendek",
    "cepet": "cepat",
    "ceu": "kakak perempuan",
    "cew": "cewek",
    "cewe": "cewek",
    "chuyunk": "sayang",
    "cibuk": "sibuk",
    "cimeng": "ganja",
    "cin": "cinta",
    "cipika cipiki": "cium pipi kanan cium pipi kiri",
    "ciye": "cie",
    "ciyh": "sih",
    "ckck": "ck",
    "ckepp": "cakep",
    "ckp": "cakep",
    "clbk": "cinta lama bersemi kembali",
    "cmiiw": "correct me if i'm wrong",
    "cmpr": "campur",
    "cmpur": "campur",
    "cnenk": "senang",
    "cod": "bayar ditempat",
    "cong": "banci",
    "congor": "mulut",
    "conlok": "cinta lokasi",
    "cow": "cowok",
    "cowwyy": "maaf",
    "coz": "karena",
    "cp": "siapa",
    "cpa": "siapa",
    "cpe": "capek",
    "cppe": "capek",
    "cr": "sumber",
    "cucok": "cocok",
    "cuex": "cuek",
    "cumi": "Cuma miscall",
    "cups": "culun",
    "curanmor": "pencurian kendaraan bermotor",
    "curcol": "curahan hati colongan",
    "cwek": "cewek",
    "cyin": "cinta",
    "d": "di",
    "dah": "deh",
    "dapet": "dapat",
    "de": "adik",
    "dek": "adik",
    "demen": "suka",
    "deyh": "deh",
    "dgn": "dengan",
    "diancurin": "dihancurkan",
    "dimaafin": "dimaafkan",
    "dimintak": "diminta",
    "disono": "di sana",
    "dket": "dekat",
    "dkk": "dan kawan-kawan",
    "dll": "dan lain-lain",
    "dlu": "dulu",
    "dngn": "dengan",
    "dodol": "bodoh",
    "doku": "uang",
    "dongs": "dong",
    "dpt": "dapat",
    "dri": "dari",
    "drmn": "darimana",
    "drtd": "dari tadi",
    "dst": "dan seterusnya",
    "dtg": "datang",
    "duh": "aduh",
    "duren": "durian",
    "ed": "edisi",
    "egp": "emang saya pikirin",
    "eke": "aku",
    "elu": "kamu",
    "emangnya": "memangnya",
    "emng": "memang",
    "endak": "tidak",
    "tidak": "tidak",
    "envy": "iri",
    "ex": "mantan",
    "faktakta": "fakta",
    "fax": "facsimile",
    "fifo": "first in first out",
    "folbek": "follow back",
    "fyi": "sebagai informasi",
    "gaada": "tidak ada",
    "gag": "tidak",
    "gaje": "tidak jelas",
    "gak papa": "tidak apa-apa",
    "gan": "juragan",
    "gantengsaya": "ganteng",
    "gaptek": "gagap teknologi",
    "gatek": "gagap teknologi",
    "gawe": "kerja",
    "gbs": "tidak bisa",
    "gebetan": "orang yang disuka",
    "geje": "tidak jelas",
    "gepeng": "gelandangan dan pengemis",
    "ghiy": "lagi",
    "gile": "gila",
    "gimana": "bagaimana",
    "gino": "gigi nongol",
    "githu": "gitu",
    "gj": "tidak jelas",
    "gmana": "bagaimana",
    "gn": "begini",
    "goblok": "bodoh",
    "gokil": "gila",
    "golput": "golongan putih",
    "gombal": "suka merayu",
    "gowes": "mengayuh sepeda",
    "gpl": "tidak pakai lama",
    "gpny": "tidak punya",
    "gpp": "tidak apa-apa",
    "gr": "gede rasa",
    "gretong": "gratis",
    "gretongan": "gratisan",
    "gt": "begitu",
    "gtau": "tidak tahu",
    "gtw": "tidak tahu",
    "gua": "saya",
    "gue": "saya",
    "guoblok": "goblok",
    "guys": "teman-teman",
    "gw": "saya",
    "gws": "cepat sembuh",
    "ha": "tertawa",
    "haghaghag": "tertawa",
    "haha": "tertawa",
    "hakhak": "tertawa",
    "hallow": "halo",
    "handak": "bahan peledak",
    "hankam": "pertahanan dan keamanan",
    "hansip": "pertahanan sipil",
    "happy": "bahagia",
    "hardcore": "keras",
    "hehe": "he",
    "hellow": "halo",
    "helo": "halo",
    "helow": "halo",
    "heters": "pembenci",
    "hey": "hai",
    "hi": "hai",
    "hlm": "halaman",
    "hlng": "hilang",
    "hny": "hanya",
    "hnya": "hanya",
    "hoax": "isu bohong",
    "houm": "rumah",
    "hr": "hari",
    "hrs": "harus",
    "hrus": "harus",
    "hubad": "hubungan angkatan darat",
    "hubdar": "perhubungan darat",
    "hubla": "perhubungan laut",
    "huff": "mengeluh",
    "huft": "mengeluh",
    "hum": "rumah",
    "humas": "hubungan masyarakat",
    "humz": "rumah",
    "idk": "saya tidak tahu",
    "ikon": "lambang",
    "ilang": "hilang",
    "ilfeel": "tidak suka",
    "ilfil": "tidak suka",
    "imba": "jago sekali",
    "imho": "in my humble opinion",
    "imoet": "imut",
    "imoetz": "imut",
    "indo": "indonesia",
    "info": "informasi",
    "isengin": "bercanda",
    "ista": "nista",
    "istaa": "nista",
    "item": "hitam",
    "itung": "hitung",
    "itungan": "hitungan",
    "iyala": "iya lah",
    "iye": "iya",
    "iyo": "iya",
    "ja": "saja",
    "jablay": "jarang dibelai",
    "jadiin": "jadi",
    "jadul": "jaman dulu",
    "jaim": "jaga image",
    "jancuk": "anjing",
    "jayus": "tidak lucu",
    "jd": "jadi",
    "jdi": "jadi",
    "jdikan": "jadikan",
    "jem": "jam",
    "jentelmen": "berani",
    "jg": "juga",
    "jga": "juga",
    "jgn": "jangan",
    "jgnkan": "jangankan",
    "jijay": "jijik",
    "jir": "anjing",
    "jkt": "jakarta",
    "jln": "jalan",
    "jnj": "janji",
    "jomblo": "tidak punya pacar",
    "jth": "jatuh",
    "jubir": "juru bicara",
    "jurdil": "jujur adil",
    "jutek": "galak",
    "jwb": "jawab",
    "k": "ke",
    "ka": "kakak",
    "kab": "kabupaten",
    "kabag": "kepala bagian",
    "kabor": "kabur",
    "kacian": "kasihan",
    "kacrut": "kacau",
    "kadit": "kepala direktorat",
    "kadiv": "kepala divisi",
    "kaga": "tidak",
    "kagak": "tidak",
    "kaka": "kakak",
    "kalo": "kalau",
    "kampret": "sialan",
    "kamtib": "keamanan dan ketertiban",
    "kamtibmas": "keamanan dan ketertiban masyarakat",
    "kamuh": "kamu",
    "kamuwh": "kamu",
    "kamyu": "kamu",
    "kanwil": "kantor wilayah",
    "kapt": "kapten",
    "karna": "karena",
    "kasat": "kepala satuan",
    "kasubbag": "kepala subbagian",
    "kasubbid": "kepala subbidang",
    "katrok": "kampungan",
    "kau": "kamu",
    "kayanya": "kayaknya",
    "kbar": "kabar",
    "kbr": "kabar",
    "kcian": "kasihan",
    "kdu": "harus",
    "keburu": "terlanjur",
    "kec": "kecamatan",
    "kedubes": "kedutaan besar",
    "kejurnas": "kejuaraan nasional",
    "kek": "seperti",
    "kekeuh": "keras kepala",
    "keknya": "kayaknya",
    "kel": "kelurahan",
    "keliatan": "kelihatan",
    "kemaren": "kemarin",
    "keneh": "masih",
    "kentot": "senggama",
    "kepengen": "mau",
    "kepikiran": "terpikirkan",
    "kepingin": "mau",
    "kepo": "mau tahu urusan orang",
    "kepsek": "kepala sekolah",
    "kere": "tidak punya uang",
    "kesbang": "kesatuan bangsa",
    "kesian": "kasihan",
    "kesra": "kesejahteraan rakyat",
    "ketauan": "ketahuan",
    "ketrima": "diterima",
    "keukeuh": "keras kepala",
    "kgiatan": "kegiatan",
    "khan": "kan",
    "kibul": "bohong",
    "kibus": "kaki busuk",
    "kimpoi": "kawin",
    "kk": "kakak",
    "kl": "kalau",
    "klian": "kalian",
    "klianz": "kalian",
    "klo": "kalau",
    "kloter": "kelompok terbang",
    "kluarga": "keluarga",
    "klw": "kalau",
    "klwrga": "keluarga",
    "km": "kamu",
    "kmari": "kemari",
    "kmps": "kampus",
    "kmpus": "kampus",
    "kmrn": "kemarin",
    "kn": "kan",
    "knal": "kenal",
    "knl": "kenal",
    "knp": "kenapa",
    "knpa": "kenapa",
    "koar": "teriak",
    "kodya": "kota madya",
    "kog": "kok",
    "komdis": "komisi disiplin",
    "kompi": "komputer",
    "komsov": "komunis sovyet",
    "komtiong": "komunis Tiongkok",
    "kongkow": "kumpul bareng teman-teman",
    "konjen": "konsulat jenderal",
    "kopdar": "kopi darat",
    "koq": "kok",
    "korup": "korupsi",
    "kpd": "kepada",
    "kpn": "kapan",
    "kptsan": "keputusan",
    "krenz": "keren",
    "krik": "garing",
    "krm": "kirim",
    "krn": "karena",
    "kt": "kita",
    "ktauan": "ketahuan",
    "ktipu": "tipu",
    "ktmu": "ketemu",
    "ktny": "katanya",
    "ktr": "kantor",
    "kudu": "harus",
    "kuper": "kurang pergaulan",
    "kuq": "kok",
    "kurng": "kurang",
    "kw": "imitasi",
    "ky": "seperti",
    "kyk": "seperti",
    "kykny": "kayanya",
    "la": "lah",
    "laka": "kecelakaan",
    "lam": "salam",
    "lambreta": "lambat",
    "lamp": "lampiran",
    "lansia": "lanjut usia",
    "lanud": "landasan udara",
    "lapas": "lembaga pemasyarakatan",
    "latgab": "latihan gabungan",
    "lbur": "libur",
    "lebay": "berlebihan",
    "leh": "boleh",
    "lekong": "laki-laki",
    "lelet": "lambat",
    "lemot": "lambat",
    "less": "kurang",
    "lg": "lagi",
    "lgi": "lagi",
    "lgkp": "lengkap",
    "lgsg": "langsung",
    "lht": "lihat",
    "liat": "lihat",
    "light": "terang",
    "linmas": "perlindungan masyarakat",
    "litbang": "penelitian dan pengembangan",
    "lmyan": "lumayan",
    "lmyn": "lumayan",
    "lngkp": "lengkap",
    "lo": "kamu",
    "loch": "loh",
    "loe": "kamu",
    "lol": "tertawa",
    "lola": "lambat berfikir",
    "lom": "belum",
    "louph": "cinta",
    "loupz": "cinta",
    "low": "kalau",
    "lowh": "kamu",
    "lp": "lupa",
    "lu": "kamu",
    "luber": "langsung, umum, bebas, dan rahasia",
    "luchu": "lucu",
    "luchuw": "lucu",
    "luff": "cinta",
    "lum": "belum",
    "luph": "cinta",
    "luthu": "lucu",
    "lw": "kamu",
    "lwn": "lawan",
    "lwt": "lewat",
    "maacih": "terima kasih",
    "maaciw": "terima kasih",
    "mabal": "bolos",
    "mabes": "markas besar",
    "macem": "macam",
    "macem-macem": "macam-macam",
    "macih": "masih",
    "madesu": "masa depan suram",
    "maem": "makan",
    "maen": "main",
    "magabut": "makan gaji buta",
    "mahatma": "maju sehat bersama",
    "maho": "homo",
    "mak": "ibu",
    "mak jang": "kaget",
    "makasih": "terima kasih",
    "maks": "maksimal",
    "maksain": "memaksa",
    "malah": "bahkan",
    "malem": "malam",
    "malu2in": "memalukan",
    "mam": "makan",
    "mamz": "makan",
    "maneh": "kamu",
    "manies": "manis",
    "maniez": "manis",
    "mantep": "mantap",
    "mao": "mau",
    "markus": "makelar kasus",
    "masi": "masih",
    "masukin": "masukkan",
    "masy": "masyarakat",
    "mba": "mbak",
    "mbual": "bual",
    "melu": "ikut",
    "mending": "lebih baik",
    "mepet": "dekat sekali",
    "mgkin": "mungkin",
    "mgkn": "mungkin",
    "mgu": "minggu",
    "mhn": "mohon",
    "migas": "minyak dan gas bumi",
    "miker": "minuman keras",
    "mikol": "minuman beralkohol",
    "milis": "mailing list",
    "miras": "minuman keras",
    "mksd": "maksud",
    "mlah": "malah",
    "mls": "malas",
    "mngkn": "mungkin",
    "mnolak": "tolak",
    "mnt": "minta",
    "mo": "mau",
    "moge": "motor gede",
    "mokad": "mati",
    "mokat": "mati",
    "moso": "masa",
    "mosok": "masa",
    "most": "paling",
    "mpe": "sampai",
    "msh": "masih",
    "msk": "masuk",
    "mskpn": "meskipun",
    "mslh": "masalah",
    "msng2": "masing-masing",
    "mt": "makan teman",
    "muahal": "mahal",
    "mubes": "musyawarah besar",
    "muker": "musyawarah kerja",
    "mulu": "melulu",
    "mumet": "pusing",
    "mumpung": "selagi",
    "muna": "munafik",
    "munas": "musyawarah nasional",
    "munaslub": "musyawarah nasional luar biasa",
    "munfik": "munafik",
    "muntaber": "muntah dan berak",
    "musda": "musyawarah daerah",
    "musti": "mesti",
    "muup": "maaf",
    "muupz": "maaf",
    "muuv": "maaf",
    "mw": "now watching",
    "mz": "mas",
    "n": "dan",
    "nal": "kenal",
    "nanam": "menanam",
    "nangis": "menangis",
    "nanya": "bertanya",
    "naon": "apa",
    "napa": "kenapa",
    "napi": "narapidana",
    "napol": "narapidana politik",
    "napza": "narkotika, alkohol, psikotropika, dan zat adiktif ",
    "naq": "anak",
    "narkoba": "narkotika, psikotropika, dan obat terlarang",
    "narsis": "bangga pada diri sendiri",
    "nasgor": "nasi goreng",
    "nax": "anak",
    "nda": "tidak",
    "ndak": "tidak",
    "ndiri": "sendiri",
    "ndut": "gendut",
    "ne": "ini",
    "nekolim": "neokolonialisme",
    "nekolin": "neokolonialisme",
    "nelfon": "menelepon",
    "nembak": "menyatakan cinta",
    "next": "lanjut",
    "ngabis2in": "menghabiskan",
    "ngabuburit": "menunggu berbuka puasa",
    "ngakak": "tertawa",
    "ngaku": "mengaku",
    "ngambek": "marah",
    "ngambil": "mengambil",
    "ngampus": "pergi ke kampus",
    "nganggur": "tidak punya pekerjaan",
    "ngantri": "mengantri",
    "ngapah": "kenapa",
    "ngapain": "sedang apa",
    "ngaret": "terlambat",
    "ngaruh": "berpengaruh",
    "ngasih": "memberikan",
    "ngawur": "berbicara sembarangan",
    "ngebandel": "berbuat bandel",
    "ngebully": "intimidasi",
    "ngeceng": "kumpul bareng-bareng",
    "ngegosip": "bergosip",
    "ngeh": "sadar",
    "ngehe": "kesal",
    "ngeklaim": "mengklaim",
    "ngekos": "tinggal di kos",
    "ngeksis": "menjadi eksis",
    "ngelamar": "melamar",
    "ngeles": "berkilah",
    "ngeliat": "melihat",
    "ngelidur": "menggigau",
    "ngemeng": "bicara terus-terusan",
    "ngentotin": "senggama",
    "ngerampok": "merampok",
    "ngerti": "mengerti",
    "ngga": "tidak",
    "nggak": "tidak",
    "ngibul": "berbohong",
    "ngikut": "ikut",
    "ngiler": "mau",
    "nginep": "menginap",
    "ngiri": "iri",
    "ngisi": "mengisi",
    "ngisiin": "mengisikan",
    "ngmg": "bicara",
    "ngmng": "bicara",
    "ngocol": "lucu",
    "ngomong": "bicara",
    "ngomongin": "membicarakan",
    "ngubek2": "mencari-cari",
    "ngumpet": "sembunyi",
    "ngumpul": "berkumpul",
    "ngurus": "mengurus",
    "ni": "ini",
    "nie": "ini",
    "nih": "ini",
    "nipu": "tipu",
    "niyh": "nih",
    "nmenarik": "menarik",
    "nmr": "nomor",
    "nntn": "nonton",
    "nobar": "nonton bareng",
    "np": "now playing",
    "ntar": "nanti",
    "ntn": "nonton",
    "numpuk": "bertumpuk",
    "nutupin": "menutupi",
    "nyari": "mencari",
    "nyariin": "mencari",
    "nyasar": "tersesat",
    "nyekar": "menyekar",
    "nyela": "cela",
    "nyembah": "sembah",
    "nyerang": "serang",
    "nyiapin": "mempersiapkan",
    "nyicil": "mencicil",
    "nyiram": "menyiram",
    "nyoblos": "mencoblos",
    "nyok": "ayo",
    "nyokap": "ibu",
    "o/": "oleh",
    "ogah": "tidak mau",
    "ok": "ok",
    "ol": "online",
    "ongkir": "ongkos kirim",
    "oot": "out of topic",
    "org2": "orang-orang",
    "ortu": "orang tua",
    "otda": "otonomi daerah",
    "otw": "sedang di jalan",
    "pacal": "pacar",
    "pake": "pakai",
    "pala": "kepala",
    "pansus": "panitia khusus",
    "paranoid": "takut",
    "parpol": "partai politik",
    "parte": "partai",
    "pasutri": "pasangan suami istri",
    "pd": "pada",
    "pede": "percaya diri",
    "pelatnas": "pemusatan latihan nasional",
    "pemda": "pemerintah daerah",
    "pemkot": "pemerintah kota",
    "pemred": "pemimpin redaksi",
    "penertiban": "tertib",
    "penjas": "pendidikan jasmani",
    "perda": "peraturan daerah",
    "perhatiin": "perhatikan",
    "pesenan": "pesanan",
    "pgang": "pegang",
    "pi": "tapi",
    "pilkada": "pemilihan kepala daerah",
    "pisan": "sangat",
    "pk": "penjahat kelamin",
    "plg": "paling",
    "plis": "tolong",
    "plisss": "tolong",
    "pls": "tolong",
    "pmrnth": "pemerintah",
    "pndukung": "pendukung",
    "polantas": "polisi lalu lintas",
    "ponpes": "pondok pesantren",
    "pp": "pulang pergi",
    "prg": "pergi",
    "priksa": "periksa",
    "prnh": "pernah",
    "pro": "profesional",
    "problem": "masalah",
    "psen": "pesan",
    "psn": "pesan",
    "pst": "pasti",
    "psti": "pasti",
    "pswt": "pesawat",
    "puanas": "panas",
    "pw": "posisi nyaman",
    "qmo": "kamu",
    "qmu": "kamu",
    "qt": "kita",
    "rakor": "rapat koordinasi",
    "rame": "ramai",
    "ranmor": "kendaraan bermotor",
    "raskin": "rakyat miskin",
    "re": "reply",
    "red": "redaksi",
    "ref": "referensi",
    "reg": "register",
    "rehab": "rehabilitasi",
    "rejeki": "rezeki",
    "reklamuk": "reklamasi",
    "rempong": "sulit",
    "renstra": "rencana strategis",
    "repp": "balas",
    "reskrim": "reserse kriminal",
    "restik": "reserse narkotika",
    "rhs": "rahasia",
    "rights": "benar",
    "rmh": "rumah",
    "ru": "baru",
    "rubahnn": "rubah",
    "ruko": "rumah toko",
    "rusunawa": "rumah susun sewa",
    "ruz": "terus",
    "rv": "redvelvet",
    "sadaar": "sadar",
    "saia": "saya",
    "salting": "salah tingkah",
    "sampe": "sampai",
    "samsek": "sama sekali",
    "sapose": "siapa",
    "satpam": "satuan pengamanan",
    "sbb": "sebagai berikut",
    "sbh": "sebuah",
    "sbnrny": "sebenarnya",
    "scr": "secara",
    "sdgkn": "sedangkan",
    "sdkt": "sedikit",
    "se7": "setuju",
    "sebelas dua belas": "mirip",
    "sembako": "sembilan bahan pokok",
    "sempet": "sempat",
    "sendratari": "seni drama tari",
    "sept": "september",
    "seting": "akting",
    "setting": "atur",
    "sgt": "sangat",
    "shg": "sehingga",
    "siech": "sih",
    "sikon": "situasi dan kondisi",
    "simiskin": "miskin",
    "sinetron": "sinema elektronik",
    "siramin": "siramkan",
    "sj": "saja",
    "skalian": "sekalian",
    "sklh": "sekolah",
    "skt": "sakit",
    "slesai": "selesai",
    "sll": "selalu",
    "slma": "selama",
    "slsai": "selesai",
    "sma": "sama",
    "smpt": "sempat",
    "smw": "semua",
    "sndiri": "sendiri",
    "sni": "sini",
    "sohib": "teman",
    "soljum": "sholat jumat",
    "solve": "solusi",
    "somse": "sombong sekali",
    "songong": "sombong",
    "sorry": "maaf",
    "sory": "maaf",
    "sosbud": "sosial-budaya",
    "sosek": "sosial-ekonomi",
    "sospol": "sosial-politik",
    "sotoy": "sok tahu",
    "sowry": "maaf",
    "spa": "siapa",
    "spd": "sepeda",
    "sppa": "siapa",
    "sprti": "seperti",
    "spt": "seperti",
    "spy": "supaya",
    "srtfkt": "sertifikat",
    "stelah": "setelah",
    "stiap": "setiap",
    "still": "masih",
    "stlh": "setelah",
    "subbag": "subbagian",
    "suk": "masuk",
    "sumbangin": "sumbangkan",
    "sumpek": "sempit",
    "sy": "saya",
    "syg": "sayang",
    "syp": "siapa",
    "t4": "tempat",
    "tabanas": "tabungan pembangunan nasional",
    "tahi": "kotoran",
    "taik": "tahi",
    "tajir": "kaya",
    "tak": "tidak",
    "tar": "nanti",
    "tau": "tahu",
    "tauk": "tahu",
    "taun": "tahun",
    "taw": "tahu",
    "tawh": "tahu",
    "td": "tadi",
    "tdi": "tadi",
    "tdk": "tidak",
    "te2p": "tetap",
    "teh": "kakak perempuan",
    "tekor": "rugi",
    "telat": "terlambat",
    "telkom": "telekomunikasi",
    "telmi": "telat berpikir",
    "telp": "telepon",
    "temen": "teman",
    "temen2": "teman-teman",
    "tengil": "menyebalkan",
    "tengok": "menjenguk",
    "tepar": "terkapar",
    "terbitin": "terbitkan",
    "tggu": "tunggu",
    "tgl": "tanggal",
    "tgu": "tunggu",
    "thanks": "terima kasih",
    "thankz": "terima kasih",
    "thd": "terhadap",
    "thn": "tahun",
    "thx": "terima kasih",
    "tilang": "bukti pelanggaran",
    "tilep": "tilap",
    "tioghoa": "tionghoa",
    "tipi": "TV",
    "tipiwan": "TvOne",
    "tirani": "tiran",
    "tkg": "tukang",
    "tks": "terima kasih",
    "tll": "terlalu",
    "tlp": "telepon",
    "tlpn": "telepon",
    "tls": "tulis",
    "tman": "teman",
    "tmbah": "tambah",
    "tmbh": "tambah",
    "tmen2": "teman-teman",
    "tmn2": "teman-teman",
    "tmpah": "tumpah",
    "tmph": "tumpah",
    "tmpt": "tempat",
    "tnda": "tanda",
    "tngu": "tunggu",
    "tnh": "tanah",
    "tnyta": "ternyata",
    "togel": "toto gelap",
    "tokai": "tai",
    "toserba": "toko serba ada",
    "tp": "tapi",
    "tpi": "tapi",
    "tq": "terima kasih",
    "trdhulu": "terdahulu",
    "tren": "trend",
    "trending": "trend",
    "trgntg": "tergantung",
    "trima": "terima kasih",
    "trims": "terima kasih",
    "trlalu": "terlalu",
    "trm": "terima",
    "trs": "terus",
    "trutama": "terutama",
    "ts": "penulis",
    "tsangka": "tersangka",
    "tst": "tahu sama tahu",
    "ttg": "tentang",
    "tuch": "tuh",
    "tuir": "tua",
    "tw": "tahu",
    "u": "kamu",
    "uasai": "kuasa",
    "ud": "sudah",
    "udah": "sudah",
    "ujg": "ujung",
    "ul": "ulangan",
    "unyu": "lucu",
    "uplot": "unggah",
    "urang": "saya",
    "usah": "perlu",
    "utk": "untuk",
    "valas": "valuta asing",
    "w/": "dengan",
    "wadir": "wakil direktur",
    "wamil": "wajib militer",
    "warkop": "warung kopi",
    "warteg": "warung tegal",
    "waspadalah": "waspada",
    "wat": "buat",
    "watuk": "batuk",
    "wkt": "waktu",
    "wkwkkw": "tertawa",
    "wtb": "beli",
    "wtf": "what the fuck",
    "wts": "jual",
    "wtt": "tukar",
    "xixixi": "tertawa",
    "y": "ya",
    "ya": "iya",
    "yap": "iya",
    "yaudah": "ya sudah",
    "yawdah": "ya sudah",
    "yg": "yang",
    "yl": "yang lain",
    "yo": "iya",
    "yowes": "ya sudah",
    "yup": "iya",
    "zonk": "bodoh",
}

# Kamus slang yang disesuaikan dengan dataset ulasan OVO
slang_in_df = {
    # --- Singkatan & Typo Umum ---
    "abis": "habis",
    "ad": "ada",
    "ajah": "saja",
    "ajh": "saja",
    "ampe": "sampai",
    "apdet": "update",
    "apknya": "apknya",
    "asu": "anjing",
    "baget": "banget",
    "bangat": "banget",
    "bangett": "banget",
    "bangettt": "banget",
    "bener": "benar",
    "benerr": "benar",
    "bentar": "sebentar",
    "bgt": "banget",
    "bgus": "bagus",
    "bisah": "bisa",
    "bjsa": "bisa",
    "blm": "belum",
    "blom": "belum",
    "blum": "belum",
    "bner": "benar",
    "bnget": "banget",
    "bngt": "banget",
    "bnyk": "banyak",
    "bnyak": "banyak",
    "bntu": "bantu",
    "bnk": "bank",
    "brapa": "berapa",
    "brsn": "barusan",
    "bs": "bisa",
    "bsa": "bisa",
    "buanget": "banget",
    "byr": "bayar",
    "cepet": "cepat",
    "cpt": "cepat",
    "cuma": "hanya",
    "cm": "hanya",
    "cmn": "hanya",
    "dah": "sudah",
    "dapet": "dapat",
    "dateng": "datang",
    "denger": "dengar",
    "dh": "sudah",
    "dikasih": "diberi",
    "direspon": "direspons",
    "dl": "dulu",
    "dlm": "dalam",
    "dlu": "dulu",
    "dng": "dengan",
    "dong": "dong",
    "donk": "dong",
    "dongg": "dong",
    "dpt": "dapat",
    "dri": "dari",
    "drpd": "daripada",
    "emng": "memang",
    "engga": "tidak",
    "enggak": "tidak",
    "enggk": "tidak",
    "egk": "tidak",
    "ga": "tidak",
    "gaada": "tidak ada",
    "gabisa": "tidak bisa",
    "gabisaa": "tidak bisa",
    "gada": "tidak ada",
    "gakbs": "tidak bisa",
    "gbisa": "tidak bisa",
    "gbsa": "tidak bisa",
    "gak": "tidak",
    "gakk": "tidak",
    "gausah": "tidak usah",
    "gx": "tidak",
    "gimna": "bagaimana",
    "gmn": "bagaimana",
    "gmna": "bagaimana",
    "goblog": "goblok",
    "gtu": "begitu",
    "hadeh": "haduh",
    "hadehh": "haduh",
    "hadehhh": "haduh",
    "hadeehhh": "haduh",
    "hadehhhh": "haduh",
    "hadeuh": "haduh",
    "haduhhh": "haduh",
    "hrs": "harus",
    "jangn": "jangan",
    "jd": "jadi",
    "jdi": "jadi",
    "jgn": "jangan",
    "jngan": "jangan",
    "jos": "bagus sekali",
    "joss": "bagus sekali",
    "josss": "bagus sekali",
    "jt": "juta",
    "kagak": "tidak",
    "kaga": "tidak",
    "kalok": "kalau",
    "kalu": "kalau",
    "karna": "karena",
    "kau": "kamu",
    "keliatan": "kelihatan",
    "kenpa": "kenapa",
    "kesel": "kesal",
    "kesell": "kesal",
    "kl": "kalau",
    "klau": "kalau",
    "klo": "kalau",
    "klw": "kalau",
    "klok": "kalau",
    "kluar": "keluar",
    "kmarin": "kemarin",
    "kmaren": "kemarin",
    "kmren": "kemarin",
    "kmrin": "kemarin",
    "knp": "kenapa",
    "knpa": "kenapa",
    "kog": "kok",
    "koq": "kok",
    "koplak": "bodoh",
    "krn": "karena",
    "krna": "karena",
    "kya": "seperti",
    "kyak": "kayak",
    "kyg": "kayak",
    "kyk": "seperti",
    "lbh": "lebih",
    "lelet": "lambat",
    "lemog": "lambat",
    "lemott": "lambat",
    "lemodd": "lambat",
    "lalot": "lambat",
    "lalod": "lambat",
    "dolot": "lambat",
    "lg": "lagi",
    "lgi": "lagi",
    "lo": "kamu",
    "malem": "malam",
    "males": "malas",
    "mantab": "mantap",
    "mantaf": "mantap",
    "mantapl": "mantap",
    "mantapp": "mantap",
    "mantappp": "mantap",
    "mantaaap": "mantap",
    "masi": "masih",
    "mbanking": "mobile banking",
    "mkasih": "terima kasih",
    "mksh": "terima kasih",
    "mlh": "malah",
    "mna": "mana",
    "mo": "mau",
    "msh": "masih",
    "msih": "masih",
    "msuk": "masuk",
    "msk": "masuk",
    "nda": "tidak",
    "ndak": "tidak",
    "nga": "tidak",
    "ngak": "tidak",
    "ngg": "tidak",
    "nggk": "tidak",
    "ngk": "tidak",
    "ng": "tidak",
    "ngeblank": "hang",
    "ngebleng": "hang",
    "ngelag": "lag",
    "ngeleg": "lag",
    "ngeselin": "menjengkelkan",
    "ngirim": "mengirim",
    "njir": "anjing",
    "nmor": "nomor",
    "nmr": "nomor",
    "nomernya": "nomornya",
    "nungguin": "menunggu",
    "nunggunya": "nunggu",
    "ny": "nya",
    "nyaa": "nya",
    "nyusahin": "menyusahkan",
    "orng": "orang",
    "org": "orang",
    "pakek": "pakai",
    "pkai": "pakai",
    "pke": "pakai",
    "pkek": "pakai",
    "pdahal": "padahal",
    "pdhal": "padahal",
    "pdhl": "padahal",
    "pdahal": "padahal",
    "pekok": "bodoh",
    "pls": "tolong",
    "pl": "tolong",
    "tlong": "tolong",
    "tlg": "tolong",
    "tlng": "tolong",
    "prem": "premier",
    "rb": "ribu",
    "rbu": "ribu",
    "rek": "rekening",
    "rekng": "rekening",
    "sampe": "sampai",
    "smpai": "sampai",
    "smpe": "sampai",
    "sdah": "sudah",
    "sdh": "sudah",
    "sekarng": "sekarang",
    "sekrng": "sekarang",
    "skarang": "sekarang",
    "skrg": "sekarang",
    "skrng": "sekarang",
    "sekrng": "sekarang",
    "seneng": "senang",
    "sldo": "saldo",
    "smpah": "sumpah",
    "sya": "saya",
    "taii": "tai",
    "taiii": "tai",
    "taik": "tai",
    "tetep": "tetap",
    "ttep": "tetap",
    "ttp": "tetap",
    "ttap": "tetap",
    "tf": "transfer",
    "tlong": "tolong",
    "tololl": "tolol",
    "topap": "top up",
    "topup": "top up",
    "toup": "top up",
    "tpi": "tapi",
    "tranfer": "transfer",
    "tranferan": "transferan",
    "transper": "transfer",
    "tranper": "transfer",
    "teranfer": "transfer",
    "teransaksi": "transaksi",
    "traansaksi": "transaksi",
    "trasfer": "transfer",
    "trf": "transfer",
    "trs": "terus",
    "trus": "terus",
    "truss": "terus",
    "teruss": "terus",
    "udah": "sudah",
    "udaah": "sudah",
    "uda": "sudah",
    "udh": "sudah",
    "ugrade": "upgrade",
    "upgread": "upgrade",
    "upgred": "upgrade",
    "updet": "update",
    "utk": "untuk",
    "verivikasi": "verifikasi",
    "vertifikasi": "verifikasi",
    "vertivikasi": "verifikasi",
    "verifasi": "verifikasi",
    "verfi": "verifikasi",
    "ferivikasi": "verifikasi",
    "veirfikasi": "verifikasi",
    "bertivikasi": "verifikasi",
    "perivikasinya": "verifikasinya",
    "pirivikasi": "verifikasi",
    "verivikasikalo": "verifikasi kalau",
    "verivikasinya": "verifikasinya",
    "perivikasi": "verifikasi",
    "viripikasi": "verifikasi",
    "wkwkw": "tertawa",
    "wkwkwk": "tertawa",
    "wkwkwkwk": "tertawa",
    "wkwk": "tertawa",
    "yg": "yang",

    # --- Typo Aplikasi & Fitur OVO ---
    "aflikasi": "aplikasi",
    "aolikasi": "aplikasi",
    "aplication": "aplikasi",
    "aplikaai": "aplikasi",
    "aplikasih": "aplikasi",
    "aplikasii": "aplikasi",
    "apliksii": "aplikasi",
    "aplilasi": "aplikasi",
    "aplkasi": "aplikasi",
    "aplini": "aplikasi ini",
    "amplikasinya": "aplikasinya",
    "amplikasiny": "aplikasinya",
    "aflikasii": "aplikasi",
    "ewallet": "e-wallet",
    "ewalet": "e-wallet",
    "walet": "e-wallet",
    "qiris": "qris",
    "qiuris": "qris",
    "qriss": "qris",
    "paylater": "pay later",
    "paylaternya": "pay laternya",
    "paylatter": "pay later",
    "ovopaylater": "ovo pay later",
    "ovonya": "ovonya",
    "ovoo": "ovo",
    "ovvo": "ovo",
    "ovi": "ovo",
    "ovoku": "ovo ku",
    "shopeepay": "shopee pay",
    "loadingnya": "loadingnya",
    "loding": "loading",
    "lodingny": "loadingnya",

    # --- Typo & Slang Ulasan Negatif ---
    "erorr": "error",
    "erorrr": "error",
    "errornya": "errornya",
    "erornya": "errornya",
    "burik": "buruk",
    "brengsek": "brengsek",
    "bangsat": "bangsat",
    "najis": "najis",
    "babi": "babi",
    "bego": "bodoh",
    "dongo": "bodoh",
    "sialan": "sialan",
    "ajing": "anjing",
    "anjir": "anjing",
    "cok": "anjing",
    "asu": "anjing",
    "tolol": "tolol",
    "tololl": "tolol",
    "goblog": "goblok",

    # --- Kata Gaul Positif ---
    "gacor": "bagus",
    "mantul": "mantap betul",
    "jos": "bagus sekali",
    "joss": "bagus sekali",
    "josss": "bagus sekali",
    "mantaaap": "mantap",
    "mantapp": "mantap",
    "mantappp": "mantap",
    "kereennn": "keren",
    "baguss": "bagus",
    "bagusss": "bagus",
    "bagusan": "lebih bagus",

    # --- Kata Teknis & Keuangan ---
    "topup": "top up",
    "topap": "top up",
    "toup": "top up",
    "tf": "transfer",
    "trf": "transfer",
    "tranfer": "transfer",
    "refund": "pengembalian dana",
    "cashback": "cashback",
    "transferan": "transferan",
    "saldonya": "saldonya",
    "saldoku": "saldo saya",
    "saldony": "saldonya",
    "sldo": "saldo",

    # --- Kombinasi Kata Tanpa Spasi (OVO-specific) ---
    "gaada": "tidak ada",
    "gabisa": "tidak bisa",
    "gabisaa": "tidak bisa",
    "gakbs": "tidak bisa",
    "gbisa": "tidak bisa",
    "gbsa": "tidak bisa",
    "admint": "admin",
    "adminya": "adminnya",
    "admi": "admin",
    "trimakasih": "terima kasih",
    "terimakasih": "terima kasih",
    "makasih": "terima kasih",
    "mkasih": "terima kasih",
    "mksh": "terima kasih",
    "maacih": "terima kasih",
    "ngeselin": "menjengkelkan",
    "nyusahin": "menyusahkan",
    "ngebantu": "membantu",
    "ngabisin": "menghabiskan",
    "nungguin": "menunggu",
    "ngirim": "mengirim",
    "ngisi": "mengisi",
    "ngambil": "mengambil",
    "ngapain": "sedang apa",
    "ngapa": "kenapa",
    "kembaliin": "kembalikan",
    "balikin": "kembalikan",
    "dibalikin": "dikembalikan",
    "pulangin": "kembalikan",
    "pindahin": "pindahkan",
    "benerin": "perbaiki",
    "perbaikin": "perbaiki",
    "diperbaikin": "diperbaiki",
    "dibenerin": "diperbaiki",
    "tambahin": "tambahkan",
    "nambah": "menambah",
    "naikin": "naikkan",
    "turunin": "turunkan",
    "ilangin": "hilangkan",
    "hapusin": "hapuskan",
    "aktifin": "aktifkan",
    "aktifkn": "aktifkan",
    "aktivas": "aktivasi",
    "keblokir": "terblokir",
    "terblokir": "terblokir",
    "terbelokir": "terblokir",
    "blockir": "blokir",
    "diblokir": "diblokir",
    "nyangkut": "tersangkut",
    "nyantol": "tersangkut",
    "ketahan": "tertahan",
    "nahan": "menahan",
    "nunggu": "menunggu",
    "nunggak": "menunggak",
    "ngelag": "lag",
    "ngeleg": "lag",
    "ngeblank": "hang",
    "ngebleng": "hang",

    # --- Singkatan Waktu & Umum ---
    "skrg": "sekarang",
    "skrng": "sekarang",
    "skarang": "sekarang",
    "sekrng": "sekarang",
    "sekarng": "sekarang",
    "hr": "hari",
    "bln": "bulan",
    "tgl": "tanggal",
    "smpe": "sampai",
    "smpai": "sampai",
    "ampe": "sampai",
    "dlu": "dulu",
    "dl": "dulu",
    "trs": "terus",
    "trus": "terus",
    "truss": "terus",
    "teruss": "terus",
    "terussssss": "terus",

    # --- Kata Pengisi / Ekspresi ---
    "hadeh": "haduh",
    "hadehh": "haduh",
    "hadehhh": "haduh",
    "hadeehhh": "haduh",
    "hadeuh": "haduh",
    "hadehhhhh": "haduh",
    "wih": "wah",
    "wihh": "wah",
    "waaa": "wah",
    "waahh": "wah",
    "waa": "wah",
    "anehh": "aneh",
    "anehhh": "aneh",
    "anehnya": "anehnya",
    "nyaa": "nya",
    "ny": "nya",
    "nua": "nya",
    "gimna": "bagaimana",
    "poto": "foto",
    "ntah": "entah",
    "sndri": "sendiri",
    "ndiri": "sendiri",
    "kesel": "kesal",
    "kesell": "kesal",
    "seneng": "senang",
    "malem": "malam",
    "males": "malas",
    "msh": "masih",
    "msih": "masih",
    "blom": "belum",
    "blum": "belum",
    "belom": "belum",
    "dapet": "dapat",
    "lelet": "lambat",
    "lemot": "lambat",
    "lemog": "lambat",
    "lemott": "lambat",
    "lemodd": "lambat",
    "lalot": "lambat",
    "lalod": "lambat",
    "dolot": "lambat",
    "burik": "buruk",
    "ajah": "saja",
    "ajh": "saja",
    "koq": "kok",
    "kog": "kok",
    "masi": "masih",
    "udah": "sudah",
    "udh": "sudah",
    "uda": "sudah",
    "dah": "sudah",
    "wes": "sudah",
    "sya": "saya",
    "sy": "saya",
    "gw": "saya",
    "gue": "saya",
    "gua": "saya",
    "abis": "habis",
    "bgt": "banget",
    "bngt": "banget",
    "bnget": "banget",
    "mbanget": "banget",
    "bangettt": "banget",
    "bangett": "banget",
    "bangat": "banget",
    "baget": "banget",
    "kaga": "tidak",
    "kagak": "tidak",
    "kalo": "kalau",
    "klo": "kalau",
    "klw": "kalau",
    "kl": "kalau",
    "klau": "kalau",
    "kalok": "kalau",
    "kalu": "kalau",
    "klok": "kalau",
    "knp": "kenapa",
    "knpa": "kenapa",
    "kenpa": "kenapa",
    "kmarin": "kemarin",
    "kmaren": "kemarin",
    "kmren": "kemarin",
    "kmrin": "kemarin",
    "msk": "masuk",
    "msuk": "masuk",
    "utk": "untuk",
    "byr": "bayar",
    "nmr": "nomor",
    "nmor": "nomor",
    "nomernya": "nomornya",
    "rek": "rekening",
    "rekng": "rekening",
    "tdk": "tidak",
    "tp": "tapi",
    "tpi": "tapi",
    "jgn": "jangan",
    "jngan": "jangan",
    "jangn": "jangan",
    "jd": "jadi",
    "jdi": "jadi",
    "lgsg": "langsung",
    "lngsung": "langsung",
    "langsumg": "langsung",
    "langaung": "langsung",
    "dri": "dari",
    "drpd": "daripada",
    "dgn": "dengan",
    "dng": "dengan",
    "pdhl": "padahal",
    "pdhal": "padahal",
    "pdahal": "padahal",
    "dlm": "dalam",
    "dlu": "dulu",
    "dl": "dulu",
    "bs": "bisa",
    "bsa": "bisa",
    "bisah": "bisa",
    "bjsa": "bisa",
    "daptar": "daftar",
    "dftr": "daftar",
    "lbh": "lebih",
    "levih": "lebih",
    "lebiih": "lebih",
    "sdh": "sudah",
    "sdah": "sudah",
    "brapa": "berapa",
    "bbrp": "beberapa",
    "bberapa": "beberapa",
    "bnyk": "banyak",
    "bnyak": "banyak",
    "bayak": "banyak",
    "cepaat": "cepat",
    "cepet": "cepat",
    "cpt": "cepat",
    "serig": "sering",
    "smpai": "sampai",
    "sampe": "sampai",
    "smpe": "sampai",
    "ampe": "sampai",
    "sampek": "sampai",
    "nyampe": "sampai",
    "trakhir": "terakhir",
    "seblm": "sebelum",
    "setalah": "setelah",
    "setlah": "setelah",
    "stelah": "setelah",
    "stlh": "setelah",
    "sllu": "selalu",
    "slalu": "selalu",
    "selelu": "selalu",
    "swlalu": "selalu",
    "sll": "selalu",
    "smga": "semoga",
    "moga": "semoga",
    "smua": "semua",
    "semejak": "semenjak",
    "pokokny": "pokoknya",
    "pokonya": "pokoknya",
    "pkoknya": "pokoknya",
    "paan": "apaan",
    "apaan": "apa",
    "apasi": "apa sih",
    "apasih": "apa sih",
    "knapa": "kenapa",
    "keanapa": "kenapa",
    "kenapaaa": "kenapa",
    "kenapaa": "kenapa",
    "napa": "kenapa",
    "gimana": "bagaimana",
    "gimna": "bagaimana",
    "gmn": "bagaimana",
    "gmna": "bagaimana",
    "bgm": "bagaimana",
    "bgaimna": "bagaimana",
    "bagaiman": "bagaimana",
    "piye": "bagaimana",
    "bijimane": "bagaimana",
    "makasi": "terima kasih",
    "makasih": "terima kasih",
    "trimakasih": "terima kasih",
    "terimakasih": "terima kasih",
    "mkasih": "terima kasih",
    "mksh": "terima kasih",
    "trims": "terima kasih",
    "tq": "terima kasih",
    "thx": "terima kasih",
    "maacih": "terima kasih",

    # --- Gabungan kata tanpa spasi umum di review ---
    "mantabproses": "mantap prosesnya",
    "ribetsaya": "ribet saya",
    "susahtransfer": "susah transfer",
    "gangguantolong": "gangguan tolong",
    "bisaapa": "bisa apa",
    "sekarangsudah": "sekarang sudah",
    "transferudah": "transfer sudah",
    "gagaldan": "gagal dan",
    "erornutup": "error menutup",
    "bermasalahsmua": "bermasalah semua",
    "kecewaudh": "kecewa sudah",
    "bangettolong": "banget tolong",
    "burukmau": "buruk mau",
    "masukharus": "masuk harus",
    "benartolong": "benar tolong",
    "errorselalu": "error selalu",
    "lagijangan": "lagi jangan",
    "bisaalasan": "bisa alasan",
    "terusmana": "terus mana",
    "parahsetelah": "parah setelah",
    "ujungujungnya": "ujung-ujungnya",
    "repotrepot": "repot-repot",
    "satusatu": "satu-satu",
    "sampaisampai": "sampai-sampai",
    "awalawal": "awal-awal",
    "pagisiangsore": "pagi siang sore",
    "bukasering": "buka sering",
    "prosesudah": "proses sudah",
    "bisaada": "bisa ada",
    "iniuntuk": "ini untuk",
    "nihpelayanan": "nih pelayanan",
    "sayatolong": "saya tolong",
    "sayacuma": "saya cuma",
    "bagusmempermudah": "bagus mempermudah",
    "gampangfiturnya": "gampang fiturnya",
    "mudahhemat": "mudah hemat",
    "lengkapaplikasi": "lengkap aplikasi",
    "amankeren": "aman keren",
    "praktisbuat": "praktis buat",
    "aplikainyamksh": "aplikasinya terima kasih",
    "aplikasinyajd": "aplikasinya jadi",
    "aplikasipadahal": "aplikasi padahal",
    "mobilenyakesel": "mobilenya kesal",
    "mobilekenapa": "mobile kenapa",
    "transaksigak": "transaksi tidak",
    "gangguan²": "gangguan-gangguan",
    "update²": "update terus",
    "susah²": "susah-susah",
    "cape²": "capek-capek",
    "hari²": "hari-hari",
    "berulang²": "berulang-ulang",
    "sebentar²": "sebentar-sebentar",
    "buang²": "buang-buang",
    "ngecek²": "ngecek-ngecek",
    "pembayaran²": "pembayaran-pembayaran",
    "blok²": "blok-blok",
    "awal²": "awal-awal",
    "embel²": "embel-embel",
    "nyuruh²": "nyuruh-nyuruh",
    "apa²in": "apa-apaan",
    "repott²": "repot-repot",

    # --- Kata Berulang / Penekanan Emosi ---
    "kecewaaaa": "kecewa",
    "parahhhhh": "parah",
    "parahhhhhh": "parah",
    "parahh": "parah",
    "parahhh": "parah",
    "parahhhh": "parah",
    "parahhhhhhhh": "parah",
    "parah": "parah",
    "jelassss": "jelas",
    "jelass": "jelas",
    "jelasss": "jelas",
    "jelekkk": "jelek",
    "jelekmales": "jelek malas",
    "bagusss": "bagus",
    "baguss": "bagus",
    "kereennn": "keren",
    "ampuuun": "ampun",
    "ampiuuuun": "ampun",
    "ampuunn": "ampun",
    "tolooooollll": "tolol",
    "bukaaa": "buka",
    "mobileee": "mobile",
    "terussssss": "terus",
    "lahhhhhhh": "lah",
    "tolong": "tolong",
    "tolongg": "tolong",
    "tolonglah": "tolong lah",
    "tolonglaaaah": "tolong lah",
    "pleasee": "please",
    "pliss": "tolong",
    "niiii": "nih",
    "ituuu": "itu",
    "gilaaa": "gila",
    "gilaa": "gila",
    "gilak": "gila",
    "mantappp": "mantap",
    "wkwkww": "tertawa",
    "wkwwkk": "tertawa",
    "hahahahahahahahhahaha": "haha",
    "lollllll": "haha",
    "taiiiiii": "tai",
    "taiii": "tai",
    "taikkk": "tai",
    "shittt": "sial",
    "daruratt": "darurat",

    # --- Typo Kata Sifat/Keterangan ---
    "sngat": "sangat",
    "sgat": "sangat",
    "sangatt": "sangat",
    "sanganat": "sangat",
    "sangan": "sangat",
    "sangatlah": "sangat",
    "sabgat": "sangat",
    "sagat": "sangat",
    "sanggat": "sangat",
    "blass": "sama sekali",
    "samsek": "sama sekali",
    "bget": "banget",
    "bggtttt": "banget",
    "bangettt": "banget",
    "mbanget": "banget",

    # --- Typo Kata Kerja & Kata Lain ---
    "ngilang": "menghilang",
    "nyedot": "menyedot",
    "kesedot": "tersedot",
    "nyuri": "mencuri",
    "nyoba": "mencoba",
    "nyobak": "mencoba",
    "nyari": "mencari",
    "nyimpen": "menyimpan",
    "nyangkut": "tersangkut",
    "nyampe": "sampai",
    "nyusahin": "menyusahkan",
    "ngeselin": "menjengkelkan",
    "ngabisin": "menghabiskan",
    "ngebantu": "membantu",
    "ngulang": "mengulang",
    "ngecek": "mengecek",
    "ngajuin": "mengajukan",
    "ngobrol": "mengobrol",
    "ngerasa": "merasa",
    "ngeliatin": "melihat",
    "ngeriview": "mengulas",
    "ngubungi": "menghubungi",
    "ngehubungin": "menghubungi",
    "ngeliat": "melihat",
    "ngeluh": "mengeluh",
    "ngurangin": "mengurangi",
    "ngeluarin": "mengeluarkan",
    "nemuin": "menemukan",
    "nungguin": "menunggu",
    "habisin": "menghabiskan",
    "ilangin": "menghilangkan",
    "benerin": "memperbaiki",
    "perbaikin": "memperbaiki",
    "kembaliin": "mengembalikan",
    "balikin": "mengembalikan",
    "dibalikin": "dikembalikan",
    "tambahin": "menambahkan",
    "nambah": "menambah",
    "naikin": "menaikkan",
    "pindahin": "memindahkan",
    "pindahkan": "pindahkan",
    "aktifin": "mengaktifkan",
    "aktifkn": "aktifkan",
    "hapusin": "menghapus",
    "apus": "hapus",
    "masukin": "memasukkan",
    "masukinnya": "memasukkannya",
    "keluarin": "mengeluarkan",
    "turunin": "menurunkan",
    "saranin": "menyarankan",
    "laporin": "melaporkan",
    "bkin": "membuat",
    "bikinlah": "buatlah",
    "bantuin": "membantu",
    "perbaharui": "perbarui",
    "diperbaharui": "diperbarui",
    "diprbarui": "diperbarui",
    "diperberbaiki": "diperbaiki",
    "diperbaikan": "diperbaiki",
    "dperbaiki": "diperbaiki",
    "perbaki": "perbaiki",
    "perbiki": "perbaiki",
    "dibenerin": "diperbaiki",
    "dibenahi": "dibenahi",
    "betulkan": "betulkan",
    "diakukan": "dilakukan",
    "melakuka": "melakukan",
    "mengunakan": "menggunakan",
    "mnggunakan": "menggunakan",
    "menggunkana": "menggunakan",
    "digunainn": "digunakan",
    "digunakann": "digunakan",
    "digunain": "digunakan",
    "gunain": "gunakan",
    "gunakannga": "gunakannya",
    "dikonfirm": "dikonfirmasi",
    "direspon": "direspons",
    "dihubungin": "dihubungi",
    "denger": "mendengar",
    "dateng": "datang",
    "balik": "kembali",
    "ngadu": "mengadu",
    "nelpon": "menelepon",
    "telvon": "telepon",
    "telfon": "telepon",
    "telpon": "telepon",
    "tlp": "telepon",
    "ditlp": "ditelepon",
    "nelfon": "menelepon",
    "nyoblos": "mencoblos",
    "mindahin": "memindahkan",
    "nyicil": "mencicil",
    "selesain": "selesaikan",
    "nyelesain": "menyelesaikan",
    "ubgrade": "upgrade",
    "upgread": "upgrade",
    "upgred": "upgrade",
    "updet": "update",
    "apdet": "update",
    "abdate": "update",
    "upadate": "update",
    "dupdate": "diupdate",
    "diupdate": "diupdate",
    "ngapdet": "update",
    "ugrade": "upgrade",
    "downlod": "unduh",
    "donlod": "unduh",
    "donlot": "unduh",
    "dowload": "unduh",
    "dwonload": "unduh",
    "download": "unduh",
    "didownload": "diunduh",
    "uninstall": "uninstal",
    "unistal": "uninstal",
    "install": "instal",
    "intal": "instal",
    "diinstal": "diinstal",
    "screenshot": "tangkapan layar",
    "skrinsyut": "tangkapan layar",
    "screnshot": "tangkapan layar",
    "krinsot": "tangkapan layar",
    "shott": "tangkapan layar",
    "copas": "salin tempel",
    "login": "masuk",
    "logout": "keluar",
    "log": "keluar",
    "loging": "masuk",
    "loginnya": "masuknya",
    "sign": "masuk",

    # --- Kata Baru OVO Spesifik ---
    "ngestak": "macet",
    "ngelag": "lag",
    "ngeleg": "lag",
    "ngeblank": "hang",
    "ngebleng": "hang",
    "pending": "tertunda",
    "gabisa": "tidak bisa",
    "gaada": "tidak ada",
    "gada": "tidak ada",
    "nyangkut": "tersangkut",
    "nyantol": "tersangkut",
    "keblokir": "terblokir",
    "terblokir": "terblokir",
    "terbelokir": "terblokir",
    "blockir": "blokir",
    "ketahan": "tertahan",
    "tertahan": "tertahan",
    "nahan": "menahan",
    "nunggu": "menunggu",
    "nunggak": "menunggak",
    "refund": "pengembalian dana",
    "topup": "top up",
    "topap": "top up",
    "toup": "top up",
    "ewallet": "dompet elektronik",
    "ewalet": "dompet elektronik",
    "walet": "dompet elektronik",
    "qris": "qris",
    "qiris": "qris",
    "qiuris": "qris",
    "qriss": "qris",
    "cashback": "cashback",
    "paylater": "pay later",
    "paylatter": "pay later",
    "voucher": "voucer",
    "vocer": "voucer",
    "premier": "premier",
    "premiere": "premier",
    "shopeepay": "shopee pay",
    "gopay": "gopay",
    "mbanking": "mobile banking",
    "transferan": "transferan",
    "tranferan": "transferan",
    "tf": "transfer",
    "trf": "transfer",
    "tranfer": "transfer",
    "transper": "transfer",
    "tranper": "transfer",
    "teranfer": "transfer",
    "trasfer": "transfer",
    "trasnfer": "transfer",
    "traansaksi": "transaksi",
    "teransaksi": "transaksi",
    "bertranksasi": "bertransaksi",
    "bertansaksinya": "bertransaksinya",

    # --- Typo Verifikasi ---
    "verivikasi": "verifikasi",
    "vertifikasi": "verifikasi",
    "vertivikasi": "verifikasi",
    "verifasi": "verifikasi",
    "verfi": "verifikasi",
    "ferivikasi": "verifikasi",
    "veirfikasi": "verifikasi",
    "bertivikasi": "verifikasi",
    "perivikasinya": "verifikasinya",
    "pirivikasi": "verifikasi",
    "verivikasikalo": "verifikasi kalau",
    "verivikasinya": "verifikasinya",
    "perivikasi": "verifikasi",
    "viripikasi": "verifikasi",
    "vertivikasi": "verifikasi",
    "veeifikasi": "verifikasi",
    "veripikasi": "verifikasi",
    "verivicasi": "verifikasi",
    "veirfivikasi": "verifikasi",
    "veriffikasi": "verifikasi",
    "ferivikasi": "verifikasi",
    "vrifikasiku": "verifikasiku",
    "verif": "verifikasi",
    "perivikasinya": "verifikasinya",
    "scurity": "keamanan",
    "kyc": "verifikasi identitas",
}

slangwords = {**slang_general, **slang_in_df}


def fix_slangwords(text):
    """
    Normalize slang words in a text using a predefined slang dictionary.

    Each word in the input text is checked against a combined slang dictionary.
    If a match is found, the word is replaced with its formal equivalent.
    Words not found in the dictionary are left unchanged.

    Parameters
    ----------
    text : str
        Input text that may contain slang words.

    Returns
    -------
    str
        The processed text with slang words replaced by their formal equivalents.

    Notes
    -----
    This function relies on the global variable `slangwords`, which is a
    merged dictionary of `slang_general` and `slang_in_df`. The merging
    is done via ``{**slang_general, **slang_in_df}``, meaning keys in
    `slang_in_df` will override duplicate keys from `slang_general`.

    Examples
    --------
    >>> fix_slangwords("tf saldo gw kok ga masuk")
    'transfer saldo saya kok tidak masuk'

    >>> fix_slangwords("erorr terus udah update masih sama")
    'error terus sudah update masih sama'
    """
    words = text.split()
    return " ".join(slangwords.get(word, word) for word in words)
